version: '3'
services:
  spotify:
    container_name: spotifyd
    restart: always
    #image: ghcr.io/hifiberry/extension_spotifyd:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SPOTIFY_CLIENT_ID=2c1ea588dfbc4a989e2426f8385297c3
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /usr/share/alsa:/usr/share/alsa
      - /etc/spotifyd.conf:/etc/spotifyd.conf
      - /etc/asound.conf:/etc/asound.conf
      - /etc/hifiberry.state:/etc/hifiberry.state
      - /run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    group_add:
      - 2001
